import type { Metadata } from "next";
import { Inter as GeistSans } from 'next/font/google';
import { Roboto_Mono as GeistMono } from 'next/font/google';
import "./globals.css";

const geistSans = GeistSans({ subsets: ['latin'] });
const geistMono = GeistMono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
